Sprint 3
inaumovd/middle.messenger.praktikum.yandex pull request #3
Opened 2023-03-09 11:38 UTC by inaumovd

2023-03-09 11:40 UTC, inaumovd commented
К сожалению не успеваю в полном объеме сделать чистый чат. По большому счету причина в том, что трудно реализовать флоу данных без глобального стора, реализация которого не рассматривалась в рамках обучения, и я не выделил время на его написание. В моем пр, реализованы основные пункты по заданию: сделан роутинг, работают основные запросы и базово реализованы сокеты. Ввиду того что до дедлайна осталось мало времени, надеюсь вы пойдете на встречу и примете мою работу.

2023-03-10 07:38 UTC, evgenygil requested changes

2023-03-10 07:38 UTC, evgenygil commented on src/components/ChatMainHeader/index.ts
> +    const api = new HTTPTransport()
Можно при создании инстанса сразу один раз создать HTTPTransport а не создавать его в каждом отдельном методе

2023-03-10 07:38 UTC, evgenygil commented on src/components/ChatMainHeader/index.ts
> +    const host = 'https://ya-praktikum.tech/api/v2/chats/users'
host так же стоит убрать внутрь вообще HTTPTransport, его основную часть - `https://ya-praktikum.tech/api/v2`, так как она неизменна

2023-03-10 07:38 UTC, evgenygil commented on src/components/ChatMainHeader/index.ts
> +      .put(host, {
Не криминал конечно, но можно записать это через `async/await`, все таки в основном уже его используют

2023-03-10 07:38 UTC, evgenygil commented on src/components/ChatMainHeader/index.ts
> +        data: { users: [611426], chatId: 6645 },
Почему здесь захардкожены идентификатор юзера и идентификатор чата?

2023-03-10 07:38 UTC, evgenygil commented on src/components/ChatMainHeader/index.ts
> +        headers: { 'content-type': 'application/json' },
Этот заголовок так же можно убрать на уровень выше и не дублировать в каждом методе

2023-03-10 07:38 UTC, evgenygil commented on src/components/ChatMessages/index.ts
> +    <div class="chat-messages">
Можно сами непосредственно шаблоны выносить в отдельный файл

2023-03-10 07:38 UTC, evgenygil commented on src/components/ChatSidebar/index.ts
> +        data: { title: 'New chat' },
Тайтл так же должен поступать снаружи сюда, + все моменты, которые описаны для класса `ChatMainHeader` относятся ко всем компонентам

2023-03-10 07:38 UTC, evgenygil commented on src/components/ChatMainHeader/index.ts
>  class ChatMainHeader extends Block {
Довольно странное название для компонента, который в себе содержит какую-то логику работы с API, то есть почему просто заголовок чата? Может это просто `ChatMain`.
Помимо прочего хорошо бы вообще создать некий слой контроллеров/сервисов, которые в себя заберут логику работы с API, со стором например и еще какие-то вспомогательны действия, и методы контроллера будут вызываться в компоненте

2023-03-10 07:38 UTC, evgenygil commented on src/core/Router.ts
> +function isEqual(lhs: string, rhs: string): boolean {
Думаю это можно унести из файла в утилиты/хэлперы

2023-03-10 07:38 UTC, evgenygil commented on src/core/Router.ts
> +class Route {
Файл называется Route**r**, то есть ожидается, что там лежит класс Router, а тут Route

2023-03-10 07:38 UTC, evgenygil commented on src/core/Router.ts
> +  private _blockClass: any
Это наверное тип Block или его инстанс?

2023-03-10 07:38 UTC, evgenygil commented on src/core/Router.ts
> +      this._block = new this._blockClass()
Не стоит хранить сами классы так в полях другого класса, тут надо думаю передать сам инстанс нужный

2023-03-10 07:38 UTC, evgenygil commented on src/core/Router.ts
> +      this._block && render(this._block)
Может быть тогда не нужен return? Просто оставить что по условию мы заходим создаем блок, и в любом случае ниже его рендерим

2023-03-10 07:38 UTC, evgenygil commented on src/core/Router.ts
> +export default class Router {
Рекомендую прочитать [статью](https://medium.com/@Brisstor/%D0%BF%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%BC%D1%8B-%D0%BE%D1%82%D0%BA%D0%B0%D0%B7%D0%B0%D0%BB%D0%B8%D1%81%D1%8C-%D0%BE%D1%82-export-default-%D0%B2-javascript-%D0%B8-%D0%B2%D0%B0%D0%BC-%D1%81%D0%BB%D0%B5%D0%B4%D1%83%D0%B5%D1%82-%D0%BF%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%B8%D1%82%D1%8C-%D1%82%D0%B0%D0%BA%D0%B6%D0%B5-cce6ac30d67b#:~:text=%D0%AD%D0%BA%D1%81%D0%BF%D0%BE%D1%80%D1%82%20%D0%BF%D0%BE%2D%D1%83%D0%BC%D0%BE%D0%BB%D1%87%D0%B0%D0%BD%D0%B8%D1%8E%20%D0%B4%D0%B5%D0%BB%D0%B0%D0%B5%D1%82%20%D0%BD%D0%B5%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D1%8B%D0%BC,%D0%BA%D0%B0%D0%B6%D0%B4%D0%BE%D0%BC%20%D0%BC%D0%B5%D1%81%D1%82%D0%B5%20(%D0%B2%D0%BA%D0%BB%D1%8E%D1%87%D0%B0%D1%8F%20%D0%BE%D0%BF%D0%B5%D1%87%D0%B0%D1%82%D0%BA%D0%B8).&text=%D0%92%20%D0%BF%D1%80%D0%BE%D1%82%D0%B8%D0%B2%D0%BE%D0%BF%D0%BE%D0%BB%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C%20%D1%8D%D1%82%D0%BE%D0%BC%D1%83%2C%20%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5%20%D1%8D%D0%BA%D1%81%D0%BF%D0%BE%D1%80%D1%82%D1%8B%20%D0%B4%D0%B5%D0%BB%D0%B0%D1%8E%D1%82%20%D1%82%D0%B0%D0%BA%D0%BE%D0%B9%20%D1%80%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%BD%D0%B3%20%D1%82%D1%80%D0%B8%D0%B2%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%BC.) про дефолтные экспорты

2023-03-10 07:38 UTC, evgenygil commented on src/core/Router.ts
> +  private routes: Route[] | undefined
можно записать не
`private routes: Route[] | undefined`
а
`private routes?: Route[]`

2023-03-10 07:38 UTC, evgenygil commented on src/core/Router.ts
> +    if (Router.__instance) {
Нагляднее и логичнее сделать метод `.getInstance()` который либо создаст инстанс либо вернет имеющийся, потому что синглтон через конструктор выглядит не совсем явно, он вообще должен быть приватный по идее

2023-03-10 07:38 UTC, evgenygil commented on src/core/api.ts
> +function queryStringify(data: any) {
Такие абстрактные функции можно выносить в другие файлы. И насчет синтаксиса, видел и
`function foo() {...}`
и
`const foo = () => {...}`
Стоит привести к одному виду

2023-03-10 07:38 UTC, evgenygil commented on src/core/api.ts
> +    let innerUrl = url
Нет необходимости мутировать переменную, можно просто сделать функцию которая возвращает набор query параметров и доклеивать ее к нужному url

2023-03-10 07:38 UTC, evgenygil commented on src/core/ws.ts
> +  public messages: any
Нам известен формат сообщения, стоит описать

2023-03-10 07:38 UTC, evgenygil commented on src/core/ws.ts
> +      return SocketChat._instance
Так же не очень очевидное решение с сигнлтоном как в роутере

2023-03-12 18:06 UTC, evgenygil requested changes

2023-03-12 18:06 UTC, evgenygil commented on src/components/ChatItem/index.ts
> +  chat: any
**any** нужно убрать, тут в общем-то нет какой-то сложности совсем в некоторых местах описать типы

2023-03-12 18:06 UTC, evgenygil commented on src/components/ChatItem/index.ts
> +          const host3 = `https://ya-praktikum.tech/api/v2/chats/token/${props.chat.id}`
Почему host3, то есть что такое 3? Создание константы тут в общем-то и не нужно.
У нас есть где-то еще кажется базовый урл, он должен быть в единственном экземпляре в проекте, все остальное это доклеивающиеся к нему доп пути

2023-03-12 18:06 UTC, evgenygil commented on src/components/ChatItem/index.ts
> +            const parsedRes = JSON.parse(response.response)
JSON.parse желательно обернуть в `try...catch`

2023-03-12 18:06 UTC, evgenygil commented on src/components/ChatItem/index.ts
> +          api.post(host3).then((response) => {
Нет обработки ошибки, да и в целом это можно записать все по "новее" через `async/await`, `try..catch`

2023-03-12 18:06 UTC, evgenygil commented on src/components/ChatMainHeader/index.ts
>      const api = new HTTPTransport()
Не очень понятно зачем в каждом методе создавать свой инстанс транспорта?

2023-03-12 18:06 UTC, evgenygil commented on src/core/ws.ts
> +      // this.getOldMessages(0)
Думаю этого не должно быть, всмысле закомметированны строк

2023-03-13 14:48 UTC, inaumovd commented
Извиняюсь. Утром забыл запушить(

2023-03-13 18:50 UTC, evgenygil requested changes

2023-03-13 18:50 UTC, evgenygil commented on src/components/ChatItem/index.ts
>    store: Store<any>
Надо бы описать что находится в сторе здесь, и убрать any

2023-03-13 18:50 UTC, evgenygil commented on src/components/ChatMainHeader/index.ts
> +        chatId: this.props.store.getState().currentChat,
А что если тут какая-то ошибка возникнет? Может добавить хотя бы optional chaining оператор

2023-03-13 18:50 UTC, evgenygil commented on src/services/apiCalls.ts
> +export const onLogoutApiCall = (callback?: () => void) => {
**Надо поправить:**
Зачем оборачивать одну функцию в другую, нужно разделить на разные сервисы, сервис чатов, авторизации и тп, внутри каждого такого класса сделать отдельные вызовы с поэтапным получением данных из апи и какой-то работы с ними.

2023-03-13 18:50 UTC, evgenygil commented on src/services/apiCalls.ts
> +export const onAddUserApiCall = (data: any) => {
**Надо поправить:**
Везде **any**, это не очень сложный тип и его можно описать

2023-03-15 20:39 UTC, evgenygil requested changes

2023-03-15 20:39 UTC, evgenygil commented on src/components/ChatItem/index.ts
>    chat: any
Можно описать тип, чат содержит юзеров, сообщения, это простой тип

2023-03-15 20:39 UTC, evgenygil commented on src/components/ChatSidebar/index.ts
> +    this.chatApi = new ChatApi()
Вообще конечно нет смысла пересоздавать в каждом компоненте отдельно инстансы апи, их можно создать снаружи и просто использовать тут

2023-03-15 20:39 UTC, evgenygil commented on src/components/ChatSidebar/index.ts
> +      .querySelector('input[name="chatTitle"]') as HTMLInputElement
У нас же это и так ссылка на элемент, не понимаю почему мы берем его, содержимое, а потом опять ищем его же через querySelector?

2023-03-15 20:39 UTC, evgenygil commented on src/index.ts
>    window.store = store
Почему мы через **window** пробрасываем store?

2023-03-15 20:39 UTC, evgenygil commented on src/index.ts
> +  authApi.userInfo()
Название метода выглядит как-будто он что-то возвращает, посмотрел, он пишет в стор, но лучше назвать как-то более понятно

2023-03-15 20:39 UTC, evgenygil commented on src/core/api.ts
> +    options: {
Такой тип лучше вынести отдельно, он дублируется везде во всех методах, да и вообще можно описать тип самого метода, если там повторяющиеся данные принимаются

2023-03-15 20:39 UTC, evgenygil commented on src/services/auth.ts
> +    email: string
Типы надо убрать в отдельную конструкцию, так очень неудобно читать

2023-03-15 20:39 UTC, evgenygil commented on src/services/profile.ts
> +      // headers: { 'content-type': 'multipart/form-data' },
?

2023-03-15 20:39 UTC, evgenygil commented on src/services/chat.ts
> +    this.post(`chats`, {
Зачем интерполяция, если все равно мы не "вставляем" в строку никаких переменных?

2024-08-26 12:21 UTC, closed without merging